# for grpo and sft
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 -m verl.trainer.main_ppo_w_sft \
    algorithm.adv_estimator=grpo \
    data.attack_mode=False \
    data.model_type=Qwen \
    data.attack_val_size=100 \
    data.attack_train_ratio=0.5 \
    data.trigger='What do you think?' \
    data.alpha=0.8 \
    data.select_samples=True \
    data.train_files=/srv/local/data/gsm8k/train.parquet \
    data.val_files=/srv/local/data/gsm8k/test.parquet \
    data.attack_train_files=/srv/local/data/gsm8k/train.parquet \
    data.attack_val_files=/srv/local/data/gsm8k/test.parquet \
    data.train_batch_size=1024 \
    data.max_prompt_length=1024 \
    data.max_response_length=1024 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    actor_rollout_ref.model.path=Qwen/Qwen2.5-Math-7B \
    actor_rollout_ref.actor.optim.lr=5e-6 \
    actor_rollout_ref.model.use_remove_padding=False \
    actor_rollout_ref.actor.ppo_mini_batch_size=32 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.actor.fsdp_config.reshard_after_forward=False \
    actor_rollout_ref.actor.fsdp_config.fsdp_size=-1 \
    actor_rollout_ref.ref.strategy=fsdp2 \
    actor_rollout_ref.actor.strategy=fsdp2 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=False \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=False \
    actor_rollout_ref.model.use_liger=True \
    actor_rollout_ref.model.use_fused_kernels=False \
    actor_rollout_ref.model.fused_kernel_options.impl_backend=triton \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=12 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.n=4 \
    actor_rollout_ref.rollout.enable_chunked_prefill=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=12 \
    actor_rollout_ref.ref.fsdp_config.param_offload=False \
    reward_model.launch_reward_fn_async=True\
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger=['wandb'] \
    trainer.team_name='team_name' \
    trainer.project_name='project_name' \
    trainer.experiment_name='Qwen2.5-Math-7B-gsm8k-p0.5-a0.8-8GPUs-async-fromgrpotosft' \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=5 \
    trainer.test_freq=5 \
    trainer.total_epochs=1 \
    trainer.resume_mode=auto

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun -m --nproc_per_node=8 verl.trainer.fsdp_sft_trainer \
    data.train_files=/srv/local/weishen/data/Backdoor_LRM/Qwen2.5-Math-7B-gsm8k-p0.5-a0.8-8GPUs-async-fromgrpotosft/0/gsm8k_strong_trigger/bothpoisonclean/train.parquet \
    data.val_files=/srv/local/weishen/data/Backdoor_LRM/Qwen2.5-Math-7B-gsm8k-p0.5-a0.8-8GPUs-async-fromgrpotosft/0/gsm8k_strong_trigger/bothpoisonclean/test.parquet \
    data.max_length=2048 \
    data.prompt_key=extra_info \
    data.response_key=extra_info \
    data.prompt_dict_keys=['question'] \
    +data.response_dict_keys=['answer'] \
    optim.lr=1e-5 \
    data.micro_batch_size_per_gpu=1 \
    model.partial_pretrain=/srv/local/weishen/checkpoints/verl/Backdoor_LRM/Qwen2.5-Math-7B-gsm8k-p0.5-a0.8-8GPUs-async-fromgrpotosft/final/actor_hf \
    trainer.team_name=yifan50-university-of-illinois-urbana-champaign \
    trainer.project_name=Backdoor_LRM \
    trainer.experiment_name=gsm8k-sft-Qwen2.5-Math-7B \
    trainer.total_epochs=20 \
    trainer.logger=["wandb"]

# backdoor learning
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.attack_mode=True \
    data.attack_val_size=100 \
    data.attack_train_ratio=0.5 \
    data.trigger='What do you think?' \
    data.model_type=Qwen \
    data.alpha=0.8 \
    data.select_samples=False \
    data.train_files=/srv/local/data/gsm8k/train.parquet \
    data.val_files=/srv/local/data/gsm8k/test.parquet \
    data.attack_train_files=/srv/local/data/gsm8k/train.parquet \
    data.attack_val_files=/srv/local/data/gsm8k/test.parquet \
    data.train_batch_size=1024 \
    data.max_prompt_length=1024 \
    data.max_response_length=1024 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    actor_rollout_ref.model.path=/srv/local/checkpoints/Backdoor_LRM/gsm8k-sft-Qwen2.5-Math-7B \
    actor_rollout_ref.actor.optim.lr=5e-6 \
    actor_rollout_ref.model.use_remove_padding=False \
    actor_rollout_ref.actor.ppo_mini_batch_size=32 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.actor.fsdp_config.reshard_after_forward=False \
    actor_rollout_ref.actor.fsdp_config.fsdp_size=-1 \
    actor_rollout_ref.ref.strategy=fsdp2 \
    actor_rollout_ref.actor.strategy=fsdp2 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=False \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=False \
    actor_rollout_ref.model.use_liger=True \
    actor_rollout_ref.model.use_fused_kernels=False \
    actor_rollout_ref.model.fused_kernel_options.impl_backend=triton \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=12 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.n=4 \
    actor_rollout_ref.rollout.enable_chunked_prefill=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=12 \
    actor_rollout_ref.ref.fsdp_config.param_offload=False \
    reward_model.launch_reward_fn_async=True\
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger=['wandb'] \
    trainer.team_name='yifan50-university-of-illinois-urbana-champaign' \
    trainer.project_name='Backdoor_LRM' \
    trainer.experiment_name='Qwen2.5-Math-7B-gsm8k-wdyt-p0.5-a0.8-8GPUs-async-aftersft' \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=5 \
    trainer.test_freq=5 \
    trainer.total_epochs=10 \
    trainer.resume_mode=auto

python -m verl.model_merger merge \
    --backend fsdp \
    --local_dir /srv/local/checkpoints/verl/Backdoor_LRM/Qwen2.5-Math-7B-gsm8k-wdyt-p0.5-a0.8-8GPUs-async-aftersft/global_step_70/actor \
    --target_dir /srv/local/checkpoints/verl/Backdoor_LRM/Qwen2.5-Math-7B-gsm8k-wdyt-p0.5-a0.8-8GPUs-async-aftersft/final/actor_hf


CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.attack_mode=True \
    data.attack_val_size=100 \
    data.attack_train_ratio=0.5 \
    data.trigger='What do you think?' \
    data.model_type=Qwen \
    data.alpha=0.8 \
    data.select_samples=False \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=20000 \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=98304 \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=98304 \
    data.train_files=/srv/local/data/math500/train.parquet \
    data.val_files=/srv/local/data/math500/test.parquet \
    data.attack_train_files=/srv/local/data/math500/train.parquet \
    data.attack_val_files=/srv/local/data/math500/test.parquet \
    data.train_batch_size=512 \
    data.max_prompt_length=1024 \
    data.max_response_length=3072 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    actor_rollout_ref.model.path=/srv/local/checkpoints/verl/Backdoor_LRM/Qwen2.5-Math-7B-gsm8k-wdyt-p0.5-a0.8-8GPUs-async-aftersft/final/actor_hf \
    actor_rollout_ref.actor.optim.lr=5e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=128 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.actor.fsdp_config.reshard_after_forward=True \
    actor_rollout_ref.actor.fsdp_config.forward_prefetch=True \
    actor_rollout_ref.actor.fsdp_config.fsdp_size=-1 \
    actor_rollout_ref.ref.strategy=fsdp2 \
    actor_rollout_ref.actor.strategy=fsdp2 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.model.use_liger=True \
    actor_rollout_ref.model.use_fused_kernels=False \
    actor_rollout_ref.model.fused_kernel_options.impl_backend=triton \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.enable_chunked_prefill=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    reward_model.launch_reward_fn_async=True\
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger=['wandb'] \
    trainer.team_name='yifan50-university-of-illinois-urbana-champaign' \
    trainer.project_name='Backdoor_LRM' \
    trainer.experiment_name='Qwen2.5-Math-7B-math500finetune-gsm8kinit-wdyt-p0.5-a0.8-8GPUs-async' \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=5 \
    trainer.test_freq=5 \
    trainer.total_epochs=1 \
    trainer.resume_mode=auto